#!/bin/bash

cd "$( dirname "$0" )"

unset LANG

# download files

if ! wget -q $( wget -q -O - 'http://www.fa-technik.adfc.de/code/opengeodb/' | egrep -o '<a.*href=".*\.tab"' | sed -e 's:.*href="::' -e 's:".*::' -e 's+^+http://www.fa-technik.adfc.de/code/opengeodb/+' | grep -v '[0-9]' ); then

	echo
	echo "*** Download failed ... aborting ***"
	echo
	exit 1

fi

# rename new downloaded files

for f in *.1; do mv -v "$f" "$( basename "$f" .1 )"; done

# create json files

(
	echo "UID=$( id -u "$USER" )"
	echo "GID=$( id -g "$USER" )"
) > .env

docker-compose up

# update git

git add -A .
git commit -m "update $( date )"
