#!/bin/bash

unset LANG

rm *.tab

wget $( wget -q -O - 'http://www.fa-technik.adfc.de/code/opengeodb/' | egrep -o '<a.*href=".*\.tab"' | sed -e 's:.*href="::' -e 's:".*::' -e 's+^+http://www.fa-technik.adfc.de/code/opengeodb/+' | grep -v '[0-9]' )

git add -A .
git commit -m "update $( date )"

